# Generated by Django 3.2 on 2021-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('rutaName', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
