# Generated by Django 3.2 on 2021-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='date pusblished')),
                ('cliente', models.CharField(max_length=200)),
                ('horasalida', models.CharField(max_length=200)),
                ('horallegada', models.CharField(max_length=200)),
                ('cajero', models.CharField(max_length=200)),
                ('asistente', models.CharField(max_length=200)),
                ('vehiculo', models.CharField(max_length=200)),
                ('ruta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fechaconeccion', models.CharField(max_length=50)),
                ('horasconectado', models.CharField(max_length=50)),
                ('fechatermina', models.DateTimeField(verbose_name='date pusblished')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identidad', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=200)),
                ('anio', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ViajeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inicio', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('horas', models.CharField(max_length=200)),
            ],
        ),
    ]
